En primer lugar, hemos obtenido varios datasets con información histórica de jugadores de la NBA desde la fundación de la liga hasta el año 2022 y vamos a juntarlos todos en un solo dataset para poder empezar a trabajar.

Vamos a realizar las importaciones necesarias para poder empezar a trabajar:

In [1]:
#Importamos pandas
import pandas as pd 
#Importamos numpy
import numpy as np 
#Importamos nuestro archivo de soporte
import sys
sys.path.append('../')
from Jupyters.soporte_def import *

print ("Librerias importadas")

Librerias importadas

A continuación, vamos a revisar las columnas de nuestros datasets para ver cuál es el punto en común de todos los datasets:

**Common info**

In [2]:
common_info = pd.read_csv("../Data/common_player_info.csv")
common_info.columns

Index(['person_id', 'first_name', 'last_name', 'display_first_last',
       'display_last_comma_first', 'display_fi_last', 'player_slug',
       'birthdate', 'school', 'country', 'last_affiliation', 'height',
       'weight', 'season_exp', 'jersey', 'position', 'rosterstatus',
       'games_played_current_season_flag', 'team_id', 'team_name',
       'team_abbreviation', 'team_code', 'team_city', 'playercode',
       'from_year', 'to_year', 'dleague_flag', 'nba_flag', 'games_played_flag',
       'draft_year', 'draft_round', 'draft_number', 'greatest_75_flag'],
      dtype='str')

In [3]:
common_info.head()

,person_id,first_name,last_name,display_first_last,display_last_comma_first,display_fi_last,player_slug,birthdate,school,country,...,playercode,from_year,to_year,dleague_flag,nba_flag,games_played_flag,draft_year,draft_round,draft_number,greatest_75_flag
0,76001,Alaa,Abdelnaby,Alaa Abdelnaby,"Abdelnaby, Alaa",A. Abdelnaby,alaa-abdelnaby,1968-06-24 00:00:00,Duke,USA,...,HISTADD_alaa_abdelnaby,1990.0,1994.0,N,Y,Y,1990,1,25,N
1,76003,Kareem,Abdul-Jabbar,Kareem Abdul-Jabbar,"Abdul-Jabbar, Kareem",K. Abdul-Jabbar,kareem-abdul-jabbar,1947-04-16 00:00:00,UCLA,USA,...,HISTADD_kareem_abdul-jabbar,1969.0,1988.0,N,Y,Y,1969,1,1,Y
2,1505,Tariq,Abdul-Wahad,Tariq Abdul-Wahad,"Abdul-Wahad, Tariq",T. Abdul-Wahad,tariq-abdul-wahad,1974-11-03 00:00:00,San Jose State,France,...,tariq_abdul-wahad,1997.0,2003.0,N,Y,Y,1997,1,11,N
3,949,Shareef,Abdur-Rahim,Shareef Abdur-Rahim,"Abdur-Rahim, Shareef",S. Abdur-Rahim,shareef-abdur-rahim,1976-12-11 00:00:00,California,USA,...,shareef_abdur-rahim,1996.0,2007.0,N,Y,Y,1996,1,3,N
4,76005,Tom,Abernethy,Tom Abernethy,"Abernethy, Tom",T. Abernethy,tom-abernethy,1954-05-06 00:00:00,Indiana,USA,...,HISTADD_tom_abernethy,1976.0,1980.0,N,Y,Y,1976,3,43,N

**Draft combine**

In [4]:
draft_combine = pd.read_csv("../Data/draft_combine_stats.csv")
draft_combine.columns

Index(['season', 'player_id', 'first_name', 'last_name', 'player_name',
       'position', 'height_wo_shoes', 'height_wo_shoes_ft_in',
       'height_w_shoes', 'height_w_shoes_ft_in', 'weight', 'wingspan',
       'wingspan_ft_in', 'standing_reach', 'standing_reach_ft_in',
       'body_fat_pct', 'hand_length', 'hand_width', 'standing_vertical_leap',
       'max_vertical_leap', 'lane_agility_time', 'modified_lane_agility_time',
       'three_quarter_sprint', 'bench_press', 'spot_fifteen_corner_left',
       'spot_fifteen_break_left', 'spot_fifteen_top_key',
       'spot_fifteen_break_right', 'spot_fifteen_corner_right',
       'spot_college_corner_left', 'spot_college_break_left',
       'spot_college_top_key', 'spot_college_break_right',
       'spot_college_corner_right', 'spot_nba_corner_left',
       'spot_nba_break_left', 'spot_nba_top_key', 'spot_nba_break_right',
       'spot_nba_corner_right', 'off_drib_fifteen_break_left',
       'off_drib_fifteen_top_key', 'off_drib_fifteen_break_right',
       'off_drib_college_break_left', 'off_drib_college_top_key',
       'off_drib_college_break_right', 'on_move_fifteen', 'on_move_college'],
      dtype='str')

In [5]:
draft_combine.head()

,season,player_id,first_name,last_name,player_name,position,height_wo_shoes,height_wo_shoes_ft_in,height_w_shoes,height_w_shoes_ft_in,...,spot_nba_break_right,spot_nba_corner_right,off_drib_fifteen_break_left,off_drib_fifteen_top_key,off_drib_fifteen_break_right,off_drib_college_break_left,off_drib_college_top_key,off_drib_college_break_right,on_move_fifteen,on_move_college
0,2001,12033,Adam,Allenspach,Adam Allenspach,C,83.50,6' 11.5'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2001,2240,Gilbert,Arenas,Gilbert Arenas,SG,74.25,6' 2.25'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2001,2220,Brandon,Armstrong,Brandon Armstrong,SG,75.50,6' 3.5'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2001,2203,Shane,Battier,Shane Battier,SF-PF,80.25,6' 8.25'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2001,12034,Cookie,Belcher,Cookie Belcher,SG-PG,75.00,6' 3'',NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Esta parte de la base de datos la vamos a omitir ya que el draft combine solo lo realizan jugadores americanos no lesionados por lo que esta parte se omitirá de nuestro dataset final.

**Draft history**

In [6]:
draft_history = pd.read_csv("../Data/draft_history.csv")
draft_history.columns

Index(['person_id', 'player_name', 'season', 'round_number', 'round_pick',
       'overall_pick', 'draft_type', 'team_id', 'team_city', 'team_name',
       'team_abbreviation', 'organization', 'organization_type',
       'player_profile_flag'],
      dtype='str')

In [7]:
draft_history.head()

,person_id,player_name,season,round_number,round_pick,overall_pick,draft_type,team_id,team_city,team_name,team_abbreviation,organization,organization_type,player_profile_flag
0,79299,Clifton McNeeley,1947,1,1,1,Draft,1610610031,Pittsburgh,Ironmen,PIT,Texas-El Paso,College/University,0
1,78109,Glen Selbo,1947,1,2,2,Draft,1610610035,Toronto,Huskies,HUS,Wisconsin,College/University,1
2,76649,Eddie Ehlers,1947,1,3,3,Draft,1610612738,Boston,Celtics,BOS,Purdue,College/University,1
3,79302,Walt Dropo,1947,1,4,4,Draft,1610610032,Providence,Steamrollers,PRO,Connecticut,College/University,0
4,77048,Dick Holub,1947,1,5,5,Draft,1610612752,New York,Knicks,NYK,Long Island-Brooklyn,College/University,1

**Players**

In [8]:
players = pd.read_csv("../Data/player.csv")
players.columns

Index(['id', 'full_name', 'first_name', 'last_name', 'is_active'], dtype='str')

In [9]:
players.head()

      id            full_name first_name     last_name  is_active
0  76001       Alaa Abdelnaby       Alaa     Abdelnaby          0
1  76002      Zaid Abdul-Aziz       Zaid    Abdul-Aziz          0
2  76003  Kareem Abdul-Jabbar     Kareem  Abdul-Jabbar          0
3     51   Mahmoud Abdul-Rauf    Mahmoud    Abdul-Rauf          0
4   1505    Tariq Abdul-Wahad      Tariq   Abdul-Wahad          0

**Players_general**

In [10]:
players_general = pd.read_csv("../Data/players_general.csv")
players_general.columns

Index(['game_id', 'player_id', 'first_name', 'last_name', 'jersey_num',
       'team_id', 'team_city', 'team_name', 'team_abbreviation'],
      dtype='str')

In [11]:
players_general.head()

,game_id,player_id,first_name,last_name,jersey_num,team_id,team_city,team_name,team_abbreviation
0,29600034,184,Bobby,Phills,14.0,1610612739,Cleveland,Cavaliers,CLE
1,29600034,781,Will,Perdue,41.0,1610612759,San Antonio,Spurs,SAS
2,29600132,120,Steven,Smith,8.0,1610612737,Atlanta,Hawks,ATL
3,29600203,698,Eddie,Johnson,8.0,1610612754,Indiana,Pacers,IND
4,29600213,32,Clifford,Rozier,44.0,1610612753,Orlando,Magic,ORL

A continuación, vamos a juntar los 5 datasets en uno solo a través de las columnas player_id y person_id ya que parece que contienen los id de todos los jugadores. Para ello vamos a seguir los siguientes pasos:

***Paso 1 --> Normalizamos el nombre de las columnas player_id y person_id***

Para normalizarla vamos a hacer uso de una función previamente definida con la misión de renombrar columnas:

In [12]:
common_info = renombrar_columnas (common_info, 'person_id', 'id')
common_info.columns

Nombre de la columna cambiado de person_id a id

Index(['id', 'first_name', 'last_name', 'display_first_last',
       'display_last_comma_first', 'display_fi_last', 'player_slug',
       'birthdate', 'school', 'country', 'last_affiliation', 'height',
       'weight', 'season_exp', 'jersey', 'position', 'rosterstatus',
       'games_played_current_season_flag', 'team_id', 'team_name',
       'team_abbreviation', 'team_code', 'team_city', 'playercode',
       'from_year', 'to_year', 'dleague_flag', 'nba_flag', 'games_played_flag',
       'draft_year', 'draft_round', 'draft_number', 'greatest_75_flag'],
      dtype='str')

In [13]:
draft_history = renombrar_columnas(draft_history, 'person_id', 'id')
draft_history.columns

Nombre de la columna cambiado de person_id a id

Index(['id', 'player_name', 'season', 'round_number', 'round_pick',
       'overall_pick', 'draft_type', 'team_id', 'team_city', 'team_name',
       'team_abbreviation', 'organization', 'organization_type',
       'player_profile_flag'],
      dtype='str')

In [14]:
players.columns

Index(['id', 'full_name', 'first_name', 'last_name', 'is_active'], dtype='str')

In [15]:
players_general = renombrar_columnas(players_general, 'player_id', 'id')
players_general.columns

Nombre de la columna cambiado de player_id a id

Index(['game_id', 'id', 'first_name', 'last_name', 'jersey_num', 'team_id',
       'team_city', 'team_name', 'team_abbreviation'],
      dtype='str')

***Paso 2 --> Unimos las tablas***

Uniremos la tabla de players_general con el resto de tablas para conservar el máximo de información posible

In [16]:
#Unimos las dos primeras tablas
player_def = pd.merge(players_general, players, on= 'id', how= 'left')
player_def.columns

Index(['game_id', 'id', 'first_name_x', 'last_name_x', 'jersey_num', 'team_id',
       'team_city', 'team_name', 'team_abbreviation', 'full_name',
       'first_name_y', 'last_name_y', 'is_active'],
      dtype='str')

In [17]:
#Unimos ahora la información histórica del draft
players_def2 = pd.merge(player_def, draft_history, on= 'id', how= 'left')
player_def.columns

Index(['game_id', 'id', 'first_name_x', 'last_name_x', 'jersey_num', 'team_id',
       'team_city', 'team_name', 'team_abbreviation', 'full_name',
       'first_name_y', 'last_name_y', 'is_active'],
      dtype='str')

Para unificar la última base de datos tenemos que realizar una limpieza ya que hay varias columnas repetidas como podemos observar.

In [18]:
players_def2 = players_def2.drop(columns = ['first_name_x', 'last_name_x', 'first_name_y','last_name_y'])
players_def2.columns

Index(['game_id', 'id', 'jersey_num', 'team_id_x', 'team_city_x',
       'team_name_x', 'team_abbreviation_x', 'full_name', 'is_active',
       'player_name', 'season', 'round_number', 'round_pick', 'overall_pick',
       'draft_type', 'team_id_y', 'team_city_y', 'team_name_y',
       'team_abbreviation_y', 'organization', 'organization_type',
       'player_profile_flag'],
      dtype='str')

In [19]:
#Por último, unificamos los datos de common player info
players_definitivo = pd.merge(players_def2, common_info, on = 'id', how = 'left')
players_definitivo.columns

Index(['game_id', 'id', 'jersey_num', 'team_id_x', 'team_city_x',
       'team_name_x', 'team_abbreviation_x', 'full_name', 'is_active',
       'player_name', 'season', 'round_number', 'round_pick', 'overall_pick',
       'draft_type', 'team_id_y', 'team_city_y', 'team_name_y',
       'team_abbreviation_y', 'organization', 'organization_type',
       'player_profile_flag', 'first_name', 'last_name', 'display_first_last',
       'display_last_comma_first', 'display_fi_last', 'player_slug',
       'birthdate', 'school', 'country', 'last_affiliation', 'height',
       'weight', 'season_exp', 'jersey', 'position', 'rosterstatus',
       'games_played_current_season_flag', 'team_id', 'team_name',
       'team_abbreviation', 'team_code', 'team_city', 'playercode',
       'from_year', 'to_year', 'dleague_flag', 'nba_flag', 'games_played_flag',
       'draft_year', 'draft_round', 'draft_number', 'greatest_75_flag'],
      dtype='str')

In [20]:
#A continuación observamos el tamaño y los registros en la base de datos
players_definitivo.shape

(110191, 54)

Como podemos observar, la base de datos cuenta con más de 100000 y 100 columnas por lo que en la siguiente fase del proyecto tendremos que realizar la limpieza de dichos datos antes de poder realizar un EDA. Para ello vamos a exportar la base de datos y vamos a abrirnos un nuevo Jupyter para realizar la limpieza:

In [21]:
players_definitivo.to_csv('Dataframe_original', index = False)
print ('Dataframe exportado')

Dataframe exportado